import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";

const sarabun = Sarabun({
    subsets: ["latin"],
    variable: "--font-sarabun",
    weight: ["400"],
});

export const metadata: Metadata = {
    title: "ะบบจัดการหลักสูตรคอมพิวเตอร์",
    description: "Generated by เด็กคอม",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={sarabun.className}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                    <Toaster
                        position="top-right"
                        richColors
                        closeButton
                        toastOptions={{ className: sarabun.className }}
                    />
                </ThemeProvider>
            </body>
        </html>
    );
}